name: Stargazer

on: 
  pull_request:
    branches:
    - master

env:
  OPTIMISM_RPC: ${{secrets.OPTIMISM_RPC}}
  PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
  CONTRACT_ADDRESS: ${{secrets.CONTRACT_ADDRESS}}

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: update Impact score
        run: |
          export additions=${{toJSON(github.event.pull_request.additions)}};
          export contributor=$(echo "Commit body ${{toJSON(github.event.pull_request.body)}}" | grep -o -E '0x.{0,40}');
          echo $additions && echo $contributor;
          echo $
          cast send $CONTRACT_ADDRESS "updateUnits(string,address,uint128)" "stargazer" $contributor $additions --private-key $PRIVATE_KEY --rpc-url $OPTIMISM_RPC;



      # - name: Contract interaction
      #   run: | 
      #     sh script/updateUnits.sh $CONTRACT_ADDRESS $(echo "Commit body ${{toJSON(github.event.pull_request.body)}}" | grep -o -E '0x.{0,40}') $OPTIMISM_RPC $PK 

